# SITE SETTINGS
title: HiRAD
author: HiRAD partners

# SOCIAL PROFILES
social:
  github: enram

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish@3.0
posts_on_home: false
tweets_on_home: false
archive_permalink: /news/
github_edit: true
colors:
  links: "#90308B"
  banner: "#67C2C7"
  footer: "#90308B"
font_serif: true
logo: /assets/images/hirad-nav-logo.png

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      type: "pages"
    values:
      background: /assets/backgrounds/default.png
  - scope:
      type: "posts"
    values:
      permalink: "/news/:year/:slug/"
